sudo: required

services:
      - docker
language: node_js
node_js:
      - 6
cache:
      directories:
              - node_modules
script:
    - (cd frontend ; npm test)
    - (cd frontend ; npm build)
    - ./bin/test
