sudo: required
services:
- docker
language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- "(cd frontend ; npm install && npm test)"
- "(cd frontend ; npm run build)"
- "./bin/test"
before_install:
- openssl aes-256-cbc -K $encrypted_7abcd5d3cd6b_key -iv $encrypted_7abcd5d3cd6b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -zxvf *.tar.gz
- env PROJECT=reserve-my-life gcloud config set project ${PROJECT}
- gcloud auth activate-service-account --key-file client-secret.json
